### ISSUE TITLE
Add schema protections

### ISSUE THREAD

**Issue by beechnut** [beechnut/aspen#7]
Working with free text, there are minimal constraints and a single typo could lead to unpleasant issues.

Let's let Aspen users add guardrails so they can only specify certain nodes and edges.

Given this discourse:

```yaml
allow_only:
  nodes: Person, Employer
  edges: knows, works at
----
...
```
referencing any other nodes or edges in Aspen OR in Cypher templates should raise an error and prevent compilation.
